import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useUser } from "../src/context/AuthContext";
import { useRouter } from "next/router";
import { useEffect } from "react";

const About: NextPage = () => {
  const router = useRouter();
  const { user } = useUser();
  console.log("User: ", user);
  useEffect(() => {
    if (!user) {
      router.push("/auth/login");
    }
  }, [user]);
  return (
    <>
      <Head>
        <title>ログイン後のページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Typography variant="h1" gutterBottom>
        ログイン後のページ
      </Typography>
    </>
  );
};

export default About;
