import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ホーム</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Typography variant="h1" gutterBottom>
        ホーム
      </Typography>
    </>
  );
};

export default Home;
